#include<bits/stdc++.h>

using namespace std;

pair<string,int> psi;
vector<pair<string,int> > v;

int main()
{
    int n;
    scanf("%d",&n);

    string s;

    for(int i=1; i<=n; i++)
    {
        cin >> s;
        p.first=s;
        p.second=0;

        v.push_back(psi);

    }

    int amnt,ppl;
    for(int i=1; i<=v.size();i++)
    {
        cin >> s;
        cin >> amnt >> ppl;

        for(int j=0;j<v.size();j++)
        {

        }

    }




    return 0;
}
